language: python
python:
 - "3.6.1"
install: pip install -r requirements.txt
services:
  - postgresql
before_script:
  - psql -c 'create database brighteventstest;' -U postgres
script: nosetests --with-coverage --cover-package=app && coverage report
after_success: coveralls